module.exports = {
  sdk: [
    {
      type: 'autogenerated',
      dirName: 'sdk', // '.' means the current docs folder
    },
  ],
  store: [
    {
      type: 'autogenerated',
      dirName: 'store', // '.' means the current docs folder
    },
  ],
};
