// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  store: [
    {
      type: "autogenerated",
      dirName: "store",
    },
  ],
  sdk: [
    {
      type: "autogenerated",
      dirName: "sdk",
    },
  ],
  design: [
    {
      type: "autogenerated",
      dirName: "design",
    },
    {
      type: "link",
      label: "品牌素材", // 为此链接设置的标题（label）
      href: "https://www.taptap.com/about-us/brand-resources", // 站外链接（URL）
    },
  ],
  community: [
    {
      type: "autogenerated",
      dirName: "community",
    },
  ],
};

module.exports = sidebars;
