// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sdk: [
    {
      type: 'autogenerated',
      dirName: 'sdk', // '.' means the current docs folder
    },
  ],
  store: [
    {
      type: 'autogenerated',
      dirName: 'store', // '.' means the current docs folder
    },
  ],
  design: [
    {
      type: 'autogenerated',
      dirName: 'design', // '.' means the current docs folder
    },
    {
      type: 'link',
      label: '品牌素材', // 为此链接设置的标题（label）
      href: 'https://www.taptap.com/about-us/brand-resources', // 站外链接（URL）
    },
  ],
};

module.exports = sidebars;
