// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  store: [
    {
      type: "link",
      label: "关于 TapTap",
      href: "https://www.taptap.io/about-us/",
    },
    {
      type: "autogenerated",
      dirName: "store",
    },
  ],
  sdk: [
    {
      type: "autogenerated",
      dirName: "sdk",
    },
  ],
  design: [
    {
      type: "autogenerated",
      dirName: "design",
    },
    {
      type: "link",
      label: "品牌素材",
      href: "https://www.taptap.io/about-us/brand-resources",
    },
  ],
};

module.exports = sidebars;
