export const ENTRIES = [
  {
    title: 'Chat',
    description: '一个用 Swift 搭建的聊天应用。',
    link: 'https://github.com/leancloud/swift-sdk-demo',
    tag: 'iOS',
  },
  {
    title: '数据存储入门',
    description: '本教程模拟商品发布的场景，讲解 LeanCloud 数据存储的核心用法。',
    link: 'https://github.com/leancloud/StorageStarted',
    tag: 'iOS',
  },
  {
    title: 'LeanStorage Demo',
    description: '展示了 LeanCloud 数据存储 SDK 的各种基础和高级用法，帮助开发者尽快上手 SDK。',
    link: 'https://github.com/leancloud/ios-simple-demo',
    tag: 'iOS',
  },
  {
    title: 'SNS 第三方登录',
    description: 'iOS 第三方登录示例 Demo',
    link: 'https://github.com/leancloud/LeanCloudSNSDemo-iOS',
    tag: 'iOS',
  },
  {
    title: 'LeanCloud 短信',
    description: 'LeanCloud 开源的短信演示程序，功能包括发送简单的文本验证码、按照自定义模版发送复杂的文本短信、发送语音验证码、使用手机号进行账号注册登录和重置密码等。',
    link: 'https://github.com/leancloud/leancloud-smsdemo-ios',
    tag: 'iOS',
  },
  {
    title: '数据存储入门',
    description: '本教程模拟商品发布的场景，讲解 LeanCloud 数据存储的核心用法。',
    link: 'https://github.com/leancloud/StorageStarted',
    tag: 'Android',
  },
  {
    title: 'LeanStorage Demo',
    description: '展示了 LeanCloud 数据存储 SDK 的各种基础和高级用法，包括用户系统、文件上传下载、子类化、对象复杂查询等。',
    link: 'https://github.com/leancloud/android-simple-demo',
    tag: 'Android',
  },
  {
    title: 'ChatKit 聊天 UI 组件',
    description: '一个免费开源的 Android UI 聊天组件，基于 LeanCloud 实时通信 IM 服务。它将聊天的常用功能和 UI 一起提供给开发者进行二次开发。',
    link: 'https://github.com/leancloud/LeanCloudChatKit-Android',
    tag: 'Android',
  },
  {
    title: 'LeanPush Demo',
    description: '一个使用了 LeanCloud 推送消息服务的简单 Demo，直接在客户端推送消息，并自己接收。',
    link: 'https://github.com/leancloud/android-push-demo',
    tag: 'Android',
  },
  {
    title: 'Android MixPush Demo',
    description: '使用 Android 混合推送服务的简单 Demo。',
    link: 'https://github.com/leancloud/mixpush-demos',
    tag: 'Android',
  },
  {
    title: 'SNS 第三方登录',
    description: 'Android 第三方登录示例 Demo。',
    link: 'https://github.com/leancloud/LeanCloudSNSDemo-Android',
    tag: 'Android',
  },
  {
    title: '短信验证码',
    description: '使用 LeanCloud 发送和验证短信验证码。',
    link: 'https://github.com/leancloud/android-sms-demo',
    tag: 'Android',
  },
  {
    title: 'Funny Feed',
    description: 'Android 信息流 Demo 应用。',
    link: 'https://github.com/leancloud/funny-feed/',
    tag: 'Android',
  },
  {
    title: 'Flask Todo Demo',
    description: 'Flask Todo Demo 是一个云引擎的示例项目。它运行在 Python 3 上，依赖 flask 和 LeanCloud Python SDK。点击详情来查看在线 Demo。',
    link: 'https://github.com/leancloud/flask-todo-demo',
    tag: 'Python',
  },
  {
    title: '数据存储入门',
    description: '本教程模拟商品发布的场景，讲解 LeanCloud 数据存储的核心用法。',
    link: 'https://github.com/leancloud/StorageStarted',
    tag: 'Web',
  },
  {
    title: 'LeanTodo (Vue)',
    description: '使用 JavaScript 存储 SDK 与 Vue.js 实现的 LeanTodo 应用。',
    link: 'https://github.com/leancloud/leantodo-vue/',
    tag: 'Web',
  },
  {
    title: 'LeanTodo (React Hooks)',
    description: '使用 JavaScript 存储 SDK 与 React Hooks 实现的 LeanTodo 应用。',
    link: 'https://github.com/leancloud/react-hook-demo',
    tag: 'Web',
  },
  {
    title: 'FileUp (Svelte)',
    description: '使用 JavaScript 存储 SDK 与 Svelte 实现的文件上传小工具。',
    link: 'https://github.com/leancloud/fileup/',
    tag: 'Web',
  },
  {
    title: 'LeanMessage',
    description: '使用 JavaScript 即时通讯 SDK 与 Angular 实现的完整功能的聊天 WebApp',
    link: 'https://github.com/leancloud/LeanMessage-Demo',
    tag: 'Web',
  },
  {
    title: '云引擎 Todo',
    description: '使用了 Slim PHP 框架搭建的 Todo 程序。',
    link: 'https://github.com/leancloud/slim-todo-demo',
    tag: 'PHP',
  },
  {
    title: 'LeanTodo',
    description: '使用 JavaScript 存储 SDK 在微信小程序平台上实现的 LeanTodo 应用。',
    link: 'https://github.com/leancloud/leantodo-weapp',
    tag: '微信小程序',
  },
  {
    title: 'LeanTodo',
    description: '使用 JavaScript 存储 SDK 与 React Native 实现的 LeanTodo 应用。',
    link: 'https://github.com/leancloud/leantodo-react-native',
    tag: 'React Native',
  },
  {
    title: '图片上传',
    description: 'React Native 搭配 LeanCloud 文件存储服务，实现在 iOS 和 Android 客户端上传图片。',
    link: 'https://github.com/leancloud/react-native-image-upload-demo',
    tag: 'React Native',
  },
  {
    title: '消息推送',
    description: '演示了如何在 React Native for iOS 中使用 LeanCloud 推送服务。',
    link: 'https://github.com/leancloud/react-native-installation-demo',
    tag: 'React Native',
  },
  {
    title: 'LeanCN',
    description: '使用 Flutter 数据存储 SDK 开发周报请假应用',
    link: 'https://github.com/leancloud/FlutterLeaveDemo',
    tag: 'Flutter',
  },
  {
    title: '云引擎 Node.js Demo 汇总',
    description: '该项目包括了推荐的最佳实践和常用的代码片段，每个文件中都有较为详细的注释，适合云引擎的开发者来阅读和参考，所涉及的代码片段也可以直接复制到项目中使用。',
    link: 'https://github.com/leancloud/leanengine-nodejs-demos',
    tag: 'Node.js',
  },
  {
    title: '球球大作战',
    description: '使用 LeanCloud 实时对战服务 + Cocos Creator 开发的模拟《球球大作战》demo',
    link: 'https://github.com/leancloud/BallBattle-Cocos',
    tag: 'Node.js',
  },
  {
    title: '回合制在线对战',
    description: '用 LeanCloud 实时对战和 Client Engine 实现的一款回合制对战游戏',
    link: 'https://github.com/leancloud/multiplayer-turn-based-game-demo',
    tag: 'TypeScript',
  },
  {
    title: '猜拳游戏',
    description: 'LeanCloud Client Engine 服务端（Node.js）示例',
    link: 'https://github.com/leancloud/client-engine-nodejs-getting-started',
    tag: 'TypeScript',
  }
].map(entry => ({ ...entry, links: [{ label: '详细', href: entry.link }] }));
