#!/bin/sh

set -e

rm -rf i18n/en
mv i18n/eng i18n/en

rm -rf docs/*
cp -r i18n/en/docusaurus-plugin-content-docs/current/store docs/

cat<<END > sidebars.js
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  store: [
    {
      type: 'autogenerated',
      dirName: 'store', // '.' means the current docs folder
    },
  ],
};

module.exports = sidebars;
END

rm -rf versioned_sidebars
rm -rf versions.json
rm -rf versioned_docs

TDS_REGION=hk node_modules/.bin/docusaurus build --out-dir build-hk