#!/bin/sh

set -e

rm -rf i18n/en
mv i18n/eng i18n/en

rm -rf docs/*
cp -r i18n/en/docusaurus-plugin-content-docs/current/store docs/
cp -r i18n/en/docusaurus-plugin-content-docs/current/sdk docs/

cat<<END > sidebars.js
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  store: [
    {
      type: 'autogenerated',
      dirName: 'store',
    },
  ],
  sdk: [
    {
      type: 'autogenerated',
      dirName: 'sdk',
    },
  ],
};

module.exports = sidebars;
END

rm -rf versioned_sidebars
rm -rf versions.json
rm -rf versioned_docs

TDS_REGION=global node_modules/.bin/docusaurus build --out-dir build-hk