// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  store: [
    {
      type: "autogenerated",
      dirName: "store",
    },
  ],
  sdk: [
    {
      type: "autogenerated",
      dirName: "sdk",
    },
  ],
};

module.exports = sidebars;
