# Controls when the action will run. Triggers the workflow on push request for the master branch
on:
  push:
    branches: [master]
  schedule:
    - cron: '0 */2 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}

      - name: Deploy to LeanEngine
        uses: enflo/curl-action@v1.2
        with:
          curl: -X POST https://console-api.cn-n1.lcops.cn/1.1/engine/groups/web/production/version?gitTag=${{ github.sha }}&token=${{ secrets.DEPLOY_TOKEN }}
